export default {
    analyze: '分析',
    clear: '清除',
    meter_second: '米/秒',
    meter: '米',
    isEdit:'编辑',
    isEditZ:'编辑Z轴',
    zAxis: 'z-轴方向',
    visiblePositions:'坐标显示',
    longitude: '经度',
    latitude: '纬度',
    altitude: '高程',
    delete:'删除',

    analysisArea: '分析区域',
    specifyPolygon: '指定多边形区域',
    allRegionsAnalysis: '全部区域参与分析',
    allRegionsNOAnalysis: '全部区域不参与分析',
    slopeRange: '坡度区间',
    displayStyle: '显示样式',
    slope: '坡度',
    terrainExcavation: '地形开挖',
    terrainModify: '地形修改',
    terrainExcavationDepth: '开挖深度(米)',
    modify: '修改',
    excavation: '开挖',
    visibleHeight: '可见高度',
    isolineInterval: '等值距(米)',
    displayMode: '显示模式',
    contourFilling: '等高线填充',
    panelFilling: '等高面填充',
    contourPanelFilling: '等高线面填充',
    noColorTable: '无颜色表',
    currentHeight: '当前高程',
    floodSpeed: '淹没速度',

    add: '添加',
    scanMode: '扫描模式',
    lineScan: '线状扫描',
    circularScan: '环状扫描',
    scanColor: '扫描颜色',
    scanTexture: '扫描纹理',
    particleSystem: '粒子',
    flameTyle: '火焰类型',
    fountainTyle: '水柱类型',
    type:'类型',
    flame: '火焰',
    ringFire: '环形火',
    jetFire: '喷射火',
    flowFire: '流淌火',
    explosionFire: '爆炸火',
    fountain: '喷泉',
    fireWater: '消防水',
    setting: '参数设置',
    ringRadius: '环形半径',
    emissionRate: '粒子数量',
    particleSize: '粒子大小',
    particleLife: '生命周期',
    speedRange: '速度范围',
    startScale: '初始比例',
    endScale: '终止比例',
    gravity: '重力',
    launchType: '发射类型',
    circularRadiation: '圆形放射',
    spheroidRadiation: '球体放射',
    conicalRadiation: '圆锥体放射',
    boxedRadiation: '盒状放射',

    scale:'缩放',
    searchLayers:'查询图层',
    positionMode:'位置模式',
    intersects:'相交',
    disjoint:'相离',
    contains:'包含',
    geometryType:'模型选择',
    box:'立方体',
    search:'查询',

    viewportOne:'视口一',
    viewportTwo:'视口二',
    viewportThree:'视口三',
    viewportFour:'视口四',
    earthShow:'地球',
    timeline:'时间轴',
    atomsphereRender:'大气渲染',
    sunShow:'太阳',
    fogEffect:'雾化效果',
    depthAgainst:'深度检测',
    shadowMap:'阴影',
    underground:'开启地下',
    frameRate:'显示帧率',
    cloud:'云层',
    skyBox:'天空盒',
    rain:'雨',
    snow:'雪',
    viewMode:'视图模式',
    surfaceTransparency:'地表透明度',
    rollerMode:'卷帘模式',
    lrRoller:'左右卷帘',
    tbRoller:'上下卷帘',
    customRoller:'自定义卷帘',
    useRoller:'使用卷帘',
    shieldLeft:'屏蔽左侧',
    shieldRight:'屏蔽右侧',
    shieldTop:'屏蔽上侧',
    shieldBottom:'屏蔽下侧',
    videoUrl:'视频路径',
    fileType:'在线或本地文件',
    horizontal:'水平视角',
    vertical:'垂直视角',
    projectDistance:'投放距离',
    clipMode:'裁剪模式',
    clipInside:'裁剪内部',
    clipOutside:'裁剪外部',
    visibleLine:'显示投放线和模型',
    projection:'投放',
    clip:'裁剪',
    lightColor:'光源颜色',
    cutoffDistance:'扩散距离',
    lightDecay:'衰减因子',
    lightIntensity:'光源强度',
    spotLightAngle:'聚光范围',
    lightModel:'光源模型',
    lightPositions:'光源坐标',
    multiViewport: '分屏显示',
    onePort: '不使用分屏',
    horizontalSnap: '水平分屏',
    verticalSnap: '垂直分屏',
    tripeSnap: '三视口',
    quadSnap: '四视口',
    flatten:'压平',
   

    facadeDistance: '立面图距离',
    facadeHeight: '立面图高度',
    setLodrange: '设置模型精细度',
    selectedLayer: '选择图层',
    noLayer: '暂无图层',
    lodrange: '缩放系数',
    setRegion: '指定范围',
    execute: '立面出图',
    fullScreen: '全屏',
    compass: '罗盘',
    zoomIn: '放大',
    zoomOut: '缩小',
    reset: '重置',
    operationType: '操作类型',
    stretch_cut: '拉伸与剖切',
    drilling: '钻孔',
    stretchHeight: '拉伸高度',
    drawLine: '画线',
    cut: '剖切',
    drillRadius: '钻孔半径',
    drillHeight: '钻孔深度',
    drawClip: '绘制裁剪',
    boxClip: 'Box裁剪',

    foreColor: '前景色',
    lineColor: '线颜色',
    selectedColor: '选中色',
    selectColorMode: '选中色模式',
    mix: '混合',
    replace: '替换',
    bottomAltitude: '底部高层',
    layerTrans: '图层透明度',
    fillStyle: '填充风格',
    visibleDistanceMin: '最小可见距离',
    visibleDistanceMax: '最大可见距离',
    noS3mLayer:'暂无s3m图层',

    selectedoffset:'选中偏移',
    offsetX:'沿X轴偏移',
    offsetY:'沿Y轴偏移',
    offsetZ:'沿Z轴偏移',
    polygonOffset:'多边形偏移',
    polygonOffsetFactor:'偏移因子',
    polygonOffsetUnit:'偏移量',
    brightness:'亮度',
    contrast:'对比度',
    hue:'色调',
    saturation:'饱和度',
    gamma:'伽马',
    closeShadow:'关闭阴影',
    openShadow:'开启阴影',
    shadowDarkness:'阴影明暗度',
    selectEnabled:'是否可选',
    multiChoose:'多选',
    cullEnabled:'双面渲染',
    visibility:'可见性',
    onlyShowSlection: '仅选中对象可见',
    onlyHideSlection: '仅选中对象隐藏',
    showAll: '显示全部',
    noImgLayer:'暂无影像图层',
    alpha:'透明度',
    transparentColor:'透明色',
    transparentColorTolerance:'透明色容限',
    

    designatedRoute:'指定路线',
    customRoute:'自定义路线',
    routeType:'路线选择',
    selectFlyRouteFile:'选择飞行线路文件',
    selectStop:'站点选择',
    showRoute:'显示路线',
    showStop:'显示站点',
    pause:'暂停',
    stop:'结束',
    start:'开始',
    flySpeed:'飞行速度',
    addedStops:'已添站点',
    save:'保存',
    customRouteOperating:'自定义路线操作',
    downLoad:'下载',

    polyline:'绘制线',
    polygon:'绘制面',
    drawModle:'绘制模式',
    space:'空间模式',
    stick:'贴地模式',
    postObject:'贴对象模式',
    lineColor:'线颜色',
    lineWidth:'线宽度',
    dottedColor:'间隔颜色',
    dottedLength:'分量长度',
    outLineColor:'轮廓颜色',
    outLineWidth:'轮廓宽度',
    glowStrength:'光晕强度',
    trailPercentage:'尾迹占比',
    polygonColor:'面颜色',
    downLoad:'网格线宽',
    gridCount:'网格线数',
    gridCellAlpha:'单元透明度',
    stripeEvenColor:'偶数带颜色',
    stripeOddColor:'基数带颜色',
    stripeRepeat:'带条重复数',
    stripeOffset:'带条偏移量',
    downstripeOrientationLoad:'带条水平方向',
    stripeOrientation:'带条垂直方向',
    draw:'绘制',
    symbolType:'符号类型',
    symbolColor:'符号颜色',
    addType:'添加模式',
    singleAdd:'单个添加',
    lineAdd:'沿线添加',
    faceAdd:'区域添加',
    spacing:'间距',
    number:'数量',
    Xrotation: '绕X轴旋转（°）',
    Yrotation: '绕Y轴旋转（°）',
    Zrotation: '绕Z轴旋转（°）',
    ClipWidth: '裁剪宽度（米）',
    ClipHeight: '裁剪高度（米）',

    displayVisualsBody: '显示可视体',
    displayInvisibleBody: '显示不可视体',
    viewshedAnimation:'动态可视域',
    polylineShow:'线显示',
    polygonShow:'面显示',
    bodyShow:'体显示',
    graphDisplay: '二维显示',
    limitBody:'限高体',
    title1:'播放一天时间段内阳光和阴影动画',
    title2:'播放一年的阳光和阴影动画',
    title0:'停止动画',
    daylightFilter:'采光率过滤',
    shadowShow:'显示阴影',
    profileInformation: '剖面信息',
    observeRadius:'观察半径',
    allShow:'全部显示',
    visibleShow:'可视部分',
    hiddenShow:'不可视部分',
    selectMode:'模式选择',
    measureSpace:'空间量算',
    measureGround:'贴地量算',
    planeProjection:'平面投影',
    measureDistance:'测距',
    measureHeight:'测高',
    measureSurface:'测面',
    showContour: '显示等高线',
}
