export default {
    showRenderLoopErrors:'渲染时发生错误，已停止渲染。',
    AttributeError:'该组件props没有这个属性：',
    NoPickPositionSupported:"不支持深度纹理,无法绘制多边形，地形操作功能无法使用！",
    NoTerrain:"请在地形里使用地形组件！",
    initViewerWarn:'请先初始化viewer!',
    MoveMouseHeightBox:'点击鼠标左键结束矩形绘制，移动鼠标绘制box高度',
    RightClickEndDrawing: '右键单击结束绘制',
    LeftClickBottomBox:'点击鼠标左键，开始绘制矩形作为box底面',
    ClickModelAddBox:'点击模型，添加裁剪盒子',
    SkyLineWarn: "获取天际线体前，请先绘制天际线！",
    SkyLineBody:'天际线体',
    ShadowqueryWarn:"此操作需要先开启阴影！",
    VeiwshedBody:'可视体',
    VeiwshedBodyHidden:'不可视体',
    EchartsErr: "二维显示需要echarts支持，未找到相关依赖！",
    BaseMapImg:'底图',

    tip1: '<p>点击左键确定操作区域中间点</p><p>右键单击结束绘制</p>',
}